[package]
authors = ["Aramis Razzaghipour <aramisnoah@gmail.com>"]
edition = "2018"
name = "journal"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
etcetera = "0.3.2"
itertools = "0.10.0"
serde = {version = "1.0", features = ["derive"]}
tempfile = "3.2"
